### ISSUE TITLE
add package json

### ISSUE THREAD

**Issue by gabrielpconceicao** [browser-packages/array-sort#2]

**Comment by cusspvz** [comment]
At least define these params:

Author: `Gabriel Conceição <gabriel.conceicao@findhit.com>`
Contributors:
- `Gabriel Conceição <gabriel.conceicao@findhit.com>`
- `José Moreira <gabriel.conceicao@findhit.com>`
- `Hugo Passo <hugo.passo@findhit.com>`

name: `bp-array-sort`
description: `bp-array-sort is a failover implemenations for faulty Array.prototype.sort method browser's implementation`
